import type { Draft, Opportunity, ReviewerPackage } from "../../types";
import { contentTypeDisplayName, draftFormatLabel, platformDisplayName } from "../../lib/forms";

type DraftPreviewPanelProps = {
  draft: Draft;
  selectedOpportunity: Opportunity | null;
  reviewPackage: ReviewerPackage | null;
  previewParagraphs: string[];
  supportedClaimCount: number;
  unsupportedClaimCount: number;
  duplicateMatchCount: number;
  selectedDraftAdapter: string;
  selectedDraftPromptVersion: string;
};

export function DraftPreviewPanel({
  draft,
  selectedOpportunity,
  reviewPackage,
  previewParagraphs,
  supportedClaimCount,
  unsupportedClaimCount,
  duplicateMatchCount,
  selectedDraftAdapter,
  selectedDraftPromptVersion,
}: DraftPreviewPanelProps) {
  return (
    <section className="panel band preview-panel">
      <div className="section-heading">
        <div>
          <p className="eyebrow">Preview</p>
          <h2>{platformDisplayName(draft.platform)} artifact</h2>
        </div>
        <span className="platform-count">{contentTypeDisplayName(draft.content_type)}</span>
      </div>
      <div className="preview-layout">
        <article className={`platform-preview ${draft.platform}`}>
          <div className="preview-chrome">
            <div>
              <span>{platformDisplayName(draft.platform)}</span>
              <strong>{draft.hook || draftFormatLabel(draft)}</strong>
            </div>
            <small>{draft.status.replace("_", " ")}</small>
          </div>
          <div className="preview-body">
            {previewParagraphs.length > 0 ? (
              previewParagraphs.map((paragraph, index) => <p key={`${draft.id}-paragraph-${index}`}>{paragraph}</p>)
            ) : (
              <p>{draft.body}</p>
            )}
          </div>
        </article>

        <aside className="trust-summary">
          <div className="trust-card strong">
            <span>Evidence</span>
            <strong>{draft.source_ids.length}</strong>
            <small>
              approved source{draft.source_ids.length === 1 ? "" : "s"}
            </small>
          </div>
          <div className={unsupportedClaimCount > 0 ? "trust-card warning" : "trust-card"}>
            <span>Claims</span>
            <strong>
              {supportedClaimCount}/{draft.claims.length}
            </strong>
            <small>{unsupportedClaimCount > 0 ? `${unsupportedClaimCount} need review` : "supported or non-factual"}</small>
          </div>
          <div className={draft.risk_report.length > 0 ? "trust-card warning" : "trust-card"}>
            <span>Risk</span>
            <strong>{draft.risk_report.length}</strong>
            <small>{draft.risk_report.length === 1 ? "review note" : "review notes"}</small>
          </div>
          <div className={duplicateMatchCount > 0 ? "trust-card warning" : "trust-card"}>
            <span>Memory</span>
            <strong>{duplicateMatchCount}</strong>
            <small>
              similar post{duplicateMatchCount === 1 ? "" : "s"}
            </small>
          </div>
          <div className="trust-explain">
            <span>Generated by</span>
            <strong>{selectedDraftAdapter}</strong>
            <small>{selectedDraftPromptVersion}</small>
          </div>
          {selectedOpportunity && (
            <div className="trust-explain">
              <span>Why today</span>
              <p>{selectedOpportunity.reason_today}</p>
            </div>
          )}
          {reviewPackage?.source_chunks.length ? (
            <div className="trust-evidence">
              <span>Evidence preview</span>
              {reviewPackage.source_chunks.slice(0, 2).map((chunk) => (
                <p key={chunk.id}>{chunk.chunk_text}</p>
              ))}
            </div>
          ) : null}
        </aside>
      </div>
    </section>
  );
}
